apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web1-deployment
  labels:
    app : my-k8s-deployment-web1
spec:
  #replicas: 2 # Don't need this anymore as we are using HorizontalPodAutoscaler
  selector:
    matchLabels:
      project: web1
  template:
    metadata:
      labels:
        project: web1   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : main-web1
          image: adv4000/k8sphp:latest
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-web1-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: my-web1-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
      AverageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
      AverageUtilization: 80

---
apiVersion: v1
kind: Service
metadata:
  name:  my-web1-service
  labels:
     app : my-k8s-deployment-web1
spec:
  selector:
    project: main-web1      # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on Pod
  type: LoadBalancer

  
