apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web2-deployment
  labels:
    app : my-k8s-deployment-web2
spec:
  #replicas: 2 # Don't need this anymore as we are using HorizontalPodAutoscaler
  selector:
    matchLabels:
      project: web2
  template:
    metadata:
      labels:
        project: web2   # Service will look for those PODS Labels!!!
    spec:
      containers:
        - name : main-web2
          image: adv4000/k8sphp:version2
          ports:
            - containerPort: 80

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: my-web2-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v2beta1v1
    kind: Deployment
    name: my-web2-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
         type: Utilization
         averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
         type: Utilization
         averageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name:  my-web2-service
  labels:
     app : my-k8s-deployment-web2
spec:
  selector:
    project: main-web2      # Selecting PODs with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on Pod
  type: LoadBalancer
